In [1841]:
# Importing required liberaries
import numpy as np
import pandas as pd
import os
import nltk
from nltk import tokenize
nltk.download('wordnet')
from collections import Counter
from gensim.parsing.preprocessing import remove_stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
import pandas as pd
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
import re

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [1842]:
df=pd.read_csv('BBC News Train.csv',encoding='latin-1',usecols=['ArticleId','Text','Category'])
#loading the dataset
df
df2=df


In [1843]:
#count number of words
def num_of_words(df):
    df['Text'].apply(lambda x : len(str(x).split(" ")))
    print(df[['Text']].head())
num_of_words(df)

                                                Text
0  worldcom ex-boss launches defence lawyers defe...
1  german business confidence slides german busin...
2  bbc poll indicates economic gloom citizens in ...
3  lifestyle  governs mobile choice  faster  bett...
4  enron bosses in $168m payout eighteen former e...


In [1844]:
#count number of characters
def num_of_chars(df):
    df['Text'].str.len() ## this also includes spaces
    print(df[['Text']].head())

num_of_chars(df)

                                                Text
0  worldcom ex-boss launches defence lawyers defe...
1  german business confidence slides german busin...
2  bbc poll indicates economic gloom citizens in ...
3  lifestyle  governs mobile choice  faster  bett...
4  enron bosses in $168m payout eighteen former e...


In [1845]:
#number of stop words
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [1846]:
#removing punctuation
def punctuation_removal(text):
    text=re.sub(r'[^\w\s]', '', text).replace("_"," ")
    return text
df['Text_new']=df['Text'].apply(punctuation_removal)
df

ArticleId                                               Text  \
0          1833  worldcom ex-boss launches defence lawyers defe...   
1           154  german business confidence slides german busin...   
2          1101  bbc poll indicates economic gloom citizens in ...   
3          1976  lifestyle  governs mobile choice  faster  bett...   
4           917  enron bosses in $168m payout eighteen former e...   
...         ...                                                ...   
1485        857  double eviction from big brother model caprice...   
1486        325  dj double act revamp chart show dj duo jk and ...   
1487       1590  weak dollar hits reuters revenues at media gro...   
1488       1587  apple ipod family expands market apple has exp...   
1489        538  santy worm makes unwelcome visit thousands of ...   

           Category                                           Text_new  
0          business  worldcom exboss launches defence lawyers defen...  
1          business  german business confidence slides german busin...  
2          business  bbc poll indicates economic gloom citizens in ...  
3              tech  lifestyle  governs mobile choice  faster  bett...  
4          business  enron bosses in 168m payout eighteen former en...  
...             ...                                                ...  
1485  entertainment  double eviction from big brother model caprice...  
1486  entertainment  dj double act revamp chart show dj duo jk and ...  
1487       business  weak dollar hits reuters revenues at media gro...  
1488           tech  apple ipod family expands market apple has exp...  
1489           tech  santy worm makes unwelcome visit thousands of ...  

[1490 rows x 4 columns]

In [1847]:
# removing stop words
from gensim.parsing.preprocessing import remove_stopwords
def stop_words_removal(text):
    text=remove_stopwords(text)
    return text

df['Text_new']=df['Text_new'].apply(stop_words_removal)

In [1848]:
df

ArticleId                                               Text  \
0          1833  worldcom ex-boss launches defence lawyers defe...   
1           154  german business confidence slides german busin...   
2          1101  bbc poll indicates economic gloom citizens in ...   
3          1976  lifestyle  governs mobile choice  faster  bett...   
4           917  enron bosses in $168m payout eighteen former e...   
...         ...                                                ...   
1485        857  double eviction from big brother model caprice...   
1486        325  dj double act revamp chart show dj duo jk and ...   
1487       1590  weak dollar hits reuters revenues at media gro...   
1488       1587  apple ipod family expands market apple has exp...   
1489        538  santy worm makes unwelcome visit thousands of ...   

           Category                                           Text_new  
0          business  worldcom exboss launches defence lawyers defen...  
1          business  german business confidence slides german busin...  
2          business  bbc poll indicates economic gloom citizens maj...  
3              tech  lifestyle governs mobile choice faster better ...  
4          business  enron bosses 168m payout eighteen enron direct...  
...             ...                                                ...  
1485  entertainment  double eviction big brother model caprice holb...  
1486  entertainment  dj double act revamp chart dj duo jk joel taki...  
1487       business  weak dollar hits reuters revenues media group ...  
1488           tech  apple ipod family expands market apple expande...  
1489           tech  santy worm makes unwelcome visit thousands web...  

[1490 rows x 4 columns]

In [1849]:
#converting all text to lowercase
def lower_case(text):
    text=text.lower()
    return text

df['Text_new'] = df['Text_new'].apply(lower_case)

In [1850]:
df

ArticleId                                               Text  \
0          1833  worldcom ex-boss launches defence lawyers defe...   
1           154  german business confidence slides german busin...   
2          1101  bbc poll indicates economic gloom citizens in ...   
3          1976  lifestyle  governs mobile choice  faster  bett...   
4           917  enron bosses in $168m payout eighteen former e...   
...         ...                                                ...   
1485        857  double eviction from big brother model caprice...   
1486        325  dj double act revamp chart show dj duo jk and ...   
1487       1590  weak dollar hits reuters revenues at media gro...   
1488       1587  apple ipod family expands market apple has exp...   
1489        538  santy worm makes unwelcome visit thousands of ...   

           Category                                           Text_new  
0          business  worldcom exboss launches defence lawyers defen...  
1          business  german business confidence slides german busin...  
2          business  bbc poll indicates economic gloom citizens maj...  
3              tech  lifestyle governs mobile choice faster better ...  
4          business  enron bosses 168m payout eighteen enron direct...  
...             ...                                                ...  
1485  entertainment  double eviction big brother model caprice holb...  
1486  entertainment  dj double act revamp chart dj duo jk joel taki...  
1487       business  weak dollar hits reuters revenues media group ...  
1488           tech  apple ipod family expands market apple expande...  
1489           tech  santy worm makes unwelcome visit thousands web...  

[1490 rows x 4 columns]

In [1851]:
# perform tokenization
# stemming
# lemmatization
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
def perform_tok_stemm_lemm(text):
     wordTokens=tokenize.RegexpTokenizer(r'\w+').tokenize(text)
     stemmer = PorterStemmer()
     tokens = [stemmer.stem(token) for token in wordTokens]
     finalTokens=[WordNetLemmatizer().lemmatize(w) for w in tokens]
     return finalTokens

df['Text_new'] = df['Text_new'].apply(perform_tok_stemm_lemm)
df

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


ArticleId                                               Text  \
0          1833  worldcom ex-boss launches defence lawyers defe...   
1           154  german business confidence slides german busin...   
2          1101  bbc poll indicates economic gloom citizens in ...   
3          1976  lifestyle  governs mobile choice  faster  bett...   
4           917  enron bosses in $168m payout eighteen former e...   
...         ...                                                ...   
1485        857  double eviction from big brother model caprice...   
1486        325  dj double act revamp chart show dj duo jk and ...   
1487       1590  weak dollar hits reuters revenues at media gro...   
1488       1587  apple ipod family expands market apple has exp...   
1489        538  santy worm makes unwelcome visit thousands of ...   

           Category                                           Text_new  
0          business  [worldcom, exboss, launch, defenc, lawyer, def...  
1          business  [german, busi, confid, slide, german, busi, co...  
2          business  [bbc, poll, indic, econom, gloom, citizen, maj...  
3              tech  [lifestyl, govern, mobil, choic, faster, bette...  
4          business  [enron, bos, 168m, payout, eighteen, enron, di...  
...             ...                                                ...  
1485  entertainment  [doubl, evict, big, brother, model, capric, ho...  
1486  entertainment  [dj, doubl, act, revamp, chart, dj, duo, jk, j...  
1487       business  [weak, dollar, hit, reuter, revenu, medium, gr...  
1488           tech  [appl, ipod, famili, expand, market, appl, exp...  
1489           tech  [santi, worm, make, unwelcom, visit, thousand,...  

[1490 rows x 4 columns]

In [1852]:
# printing all countof each classes
classes=Counter(df['Category'])
classes

Counter({'business': 336,
         'tech': 261,
         'politics': 274,
         'sport': 346,
         'entertainment': 273})

In [1853]:
# finding CF
def find_cf(df):
  # Create an empty dictionary to store the collection frequency of each term.
  cf_dict={}
  for index in range(len(df['Text_new'])):
    for term in df['Text_new'][index]:
      # If the current term is not already in the dictionary, add it with a frequency of 2.
      if cf_dict.get(term) is None:
        cf_dict[term]=2
        # If the term is already in the dictionary, increment its frequency by 1.
      else :
        cf_dict[term]=cf_dict[term]+1
  return cf_dict

In [1854]:
CF= find_cf(df)

In [1855]:
print(CF)

{'worldcom': 55, 'exboss': 3, 'launch': 235, 'defenc': 80, 'lawyer': 76, 'defend': 127, 'chief': 296, 'berni': 9, 'ebber': 47, 'batteri': 29, 'fraud': 101, 'charg': 226, 'call': 343, 'compani': 683, 'whistleblow': 2, 'wit': 35, 'cynthia': 3, 'cooper': 47, 's': 5917, 'exhead': 2, 'intern': 315, 'account': 204, 'alert': 37, 'director': 344, 'irregular': 13, 'practic': 55, 'telecom': 51, 'giant': 122, '2002': 107, 'warn': 248, 'led': 114, 'collaps': 42, 'firm': 676, 'follow': 345, 'discoveri': 13, '11bn': 15, 'â57bn': 4, 'mr': 2007, 'plead': 35, 'guilti': 67, 'conspiraci': 15, 'prosecut': 51, 'argu': 123, 'orchestr': 5, 'seri': 173, 'trick': 24, 'order': 201, 'employe': 47, 'hide': 23, 'expens': 66, 'inflat': 79, 'revenu': 87, 'meet': 299, 'wall': 36, 'street': 127, 'earn': 152, 'estim': 103, 'm': 449, 'run': 321, 'consult': 69, 'busi': 348, 'told': 592, 'juri': 16, 'new': 1335, 'york': 121, 'wednesday': 138, 'extern': 17, 'auditor': 16, 'arthur': 8, 'andersen': 4, 'approv': 75, 'earli': 

In [1856]:
# function to create a dictionary for each class
def dictionary_of_words(df):
  Dict= {}
  for index in range(0,len(df)):
      try:
          Dict[df['Category'][index]] = Dict[df['Category'][index]] + df['Text_new'][index]
      except:
          Dict[df['Category'][index]] = df['Text_new'][index]
  return Dict

In [1857]:
dict_of_words= dictionary_of_words(df)
dict_of_words


{'business': ['worldcom',
  'exboss',
  'launch',
  'defenc',
  'lawyer',
  'defend',
  'worldcom',
  'chief',
  'berni',
  'ebber',
  'batteri',
  'fraud',
  'charg',
  'call',
  'compani',
  'whistleblow',
  'wit',
  'cynthia',
  'cooper',
  'worldcom',
  's',
  'exhead',
  'intern',
  'account',
  'alert',
  'director',
  'irregular',
  'account',
  'practic',
  'telecom',
  'giant',
  '2002',
  'warn',
  'led',
  'collaps',
  'firm',
  'follow',
  'discoveri',
  '11bn',
  'â57bn',
  'account',
  'fraud',
  'mr',
  'ebber',
  'plead',
  'guilti',
  'charg',
  'fraud',
  'conspiraci',
  'prosecut',
  'lawyer',
  'argu',
  'mr',
  'ebber',
  'orchestr',
  'seri',
  'account',
  'trick',
  'worldcom',
  'order',
  'employe',
  'hide',
  'expens',
  'inflat',
  'revenu',
  'meet',
  'wall',
  'street',
  'earn',
  'estim',
  'm',
  'cooper',
  'run',
  'consult',
  'busi',
  'told',
  'juri',
  'new',
  'york',
  'wednesday',
  'extern',
  'auditor',
  'arthur',
  'andersen',
  'approv'

In [1858]:
print(len(dict_of_words))

5


In [1859]:
# function to find unique terms
def find_Unique(dict_of_words):
    unique_Words = set(word for words in dict_of_words.values() for word in words)
    unique_Words_Count = len(unique_Words)
    return unique_Words, unique_Words_Count

In [1860]:
# distinct_word shows the all the distict words present
# distinct_words_count is the count of distinct words
distinct_words,distinct_words_count = find_Unique(dict_of_words)

In [1861]:
# finding tf-Icf values referring to each class
import math

def tf_Icf(word_dict, cf_dict, classes_Freq):
    tfIcf = {}
    # Loop through each class in the word_dict.
    for className, doc in word_dict.items():
        termFreqDict = {}
        # Loop through each term in the document and calculate its frequency.
        for term in doc:
            if term not in termFreqDict:
                termFreqDict[term] = 0
            termFreqDict[term] += 1
        
        tf_Icf = {}
        for term, freq in termFreqDict.items():
            # Calculate the term frequency (tf).
            tf = freq / len(doc)
            # Get the collection frequency (cf) of the term from the cf_dict.
            cf = cf_dict[term]
            # Calculate the inverse class frequency (icf) of the term.
            icf = math.log(len(classes_Freq) / cf)
            # Calculate the tf-icf value of the term.
            tf_Icf[term] = tf * icf
        
        tfIcf[className] = tf_Icf
    
    return tfIcf

In [1862]:
test_TFICF = tf_Icf(dict_of_words, CF, classes)

In [1863]:
test_TFICF


{'business': {'worldcom': -0.00206165466796873,
  'exboss': 1.626651882006753e-05,
  'launch': -0.0025133512454043718,
  'defenc': -0.0007504578833263215,
  'lawyer': -0.0011265254051962042,
  'defend': -0.00025751502014301675,
  'chief': -0.010006240028198351,
  'berni': -7.486893688947015e-05,
  'ebber': -0.0016411012420063703,
  'batteri': -2.798824840467422e-05,
  'fraud': -0.003062774637891608,
  'charg': -0.004186885203748544,
  'call': -0.003971997700084044,
  'compani': -0.03068903662454157,
  'whistleblow': 1.4588990588217161e-05,
  'wit': -0.0003098237694931,
  'cynthia': 8.133259410033766e-06,
  'cooper': -0.0007135222791332044,
  's': -0.15266099464197805,
  'exhead': 1.4588990588217161e-05,
  'intern': -0.005277290399339605,
  'account': -0.00726301042898792,
  'alert': -9.560144570876449e-05,
  'director': -0.004783152608637415,
  'irregular': -0.00010649418241903059,
  'practic': -0.0004199666916232598,
  'telecom': -0.0011832503868882006,
  'giant': -0.00345871722891306

(2) Part

In [1864]:
# Splitting the dataset into train test in ratio of 70-30
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(df, test_size=0.30, random_state=43)

In [1865]:
train_data=train_data.reset_index(drop=True)
test_data= test_data.reset_index(drop=True)
train_data


ArticleId                                               Text  \
0           248  steady job growth continues in us the us creat...   
1          1034  labour s  eu propaganda  a  taxpayer subsidise...   
2          2091  oscar nominee dan o herlihy dies irish actor d...   
3           991  us in eu tariff chaos trade row the us has ask...   
4           654  lennon brands rangers favourites celtic s neil...   
...         ...                                                ...   
1038        342  u2 s desire to be number one u2  who have won ...   
1039       1518  tory backing for id cards the tories are to ba...   
1040       1439  microsoft debuts security tools microsoft is r...   
1041        283  consumers  snub portable video  consumers want...   
1042       2114  gadget show heralds mp3 christmas partners of ...   

           Category                                           Text_new  
0          business  [steadi, job, growth, continu, creat, fewer, j...  
1          politics  [labour, s, eu, propaganda, taxpay, subsidis, ...  
2     entertainment  [oscar, nomine, dan, o, herlihi, die, irish, a...  
3          business  [eu, tariff, chao, trade, row, ask, world, tra...  
4             sport  [lennon, brand, ranger, favourit, celtic, s, n...  
...             ...                                                ...  
1038  entertainment  [u2, s, desir, number, u2, won, prestigi, gram...  
1039       politics  [torus, back, id, card, torus, controversi, go...  
1040           tech  [microsoft, debut, secur, tool, microsoft, rel...  
1041           tech  [consum, snub, portabl, video, consum, want, m...  
1042           tech  [gadget, herald, mp3, christma, partner, love,...  

[1043 rows x 4 columns]

(3) and (4) Part

In [1866]:
def compute_word_freq(word, label, class_one, class_two):
    freq_one = class_one.get((label, word), 0)
    freq_two = class_two.get(label, 0)
    return freq_one, freq_two

In [1867]:
# Implementing Naive Bayes classifier with the TF-ICF weighting scheme
def naive_bayes_classifier(vocab_size, class_prior_prob, train_data, test_data, classes, class_f, class_c):
    true_labels = []
    predicted_labels = []
    
    # Iterate over each row in the test data
    for i, row in test_data.iterrows():
        true_labels.append(row['Category'])  #Actual values 
        
        # Compute the log probabilities for each class
        class_word_probs = []
        for cl in classes:
            log_prob = np.log(class_prior_prob[cl])
            for word in row['Text_new']:
                freq, count = compute_word_freq(word, cl, class_f, class_c)
                log_prob += np.log((freq + 1) / (count + vocab_size))
            class_word_probs.append(log_prob)

        # print(class_word_probs)
        # Predict the class with the highest log probability
        predicted_labels.append(classes[np.argmax(class_word_probs)]) # Pedicted values
        # print(f"Probability of {cl} given document {i} and feature set:")
        # print(f"{np.exp(class_word_probs[-1])}") 
    return true_labels, predicted_labels 


In [1868]:
# Evaluating Accuracy
def accuracy_evaluation(predValues, truthValues):
  # Sum up the number of correct predictions
    correct_predictions = sum(1 for pred, truth in zip(predValues, truthValues) if pred == truth)
    # Count the total number of predictions made
    total_predictions = len(predValues)
    # Calculate the accuracy as the proportion of correct predictions out of the total predictions
    accuracy = correct_predictions / total_predictions
    return accuracy


In [1869]:
# feature_list: a list of all features in the training data
# feature_dict: a dictionary that stores the top 200 features for each class
# class_feature_freq: a dictionary that stores the frequency of each feature for each class
# class_count: a dictionary that stores the total count of features for each class
feature_list = []
feature_dict = {}
class_feature_freq = {}
class_count = {}

# These lines initialize empty dictionaries and lists that will be used to store 
# the features of the training data, as well as the frequency of those features in each class.
for class_name in test_TFICF.keys():
    features = []
    sorted_features = sorted(test_TFICF[class_name], key=test_TFICF[class_name].get, reverse=True)
    for feature_name in sorted_features[0:int(200)]:
        feature_list.append(feature_name)
        features.append(feature_name)
        feature_dict[class_name] = features

for class_name in classes:
  # create a Counter object to count the frequency of each feature in feature_dict
    count_top_features = Counter(feature_dict[class_name])
    for feature_name in feature_list:
        class_feature_freq[class_name, feature_name] = count_top_features[feature_name]
         # store the frequency of the feature for the current class in class_feature_freq
        try:
            class_count[class_name] += count_top_features[feature_name]
        except:
            class_count[class_name] = count_top_features[feature_name]

truth_values, predicted_values = naive_bayes_classifier(distinct_words_count, classes, train_data, test_data, list(classes.keys()), class_feature_freq, class_count)
accuracy = accuracy_evaluation(predicted_values, truth_values)
print("Accuracy: ",str("{:.2f}".format(accuracy * 100)))


Accuracy:  59.06


In [1870]:
# function to calculate confusion matrix
def calculate_confusion_matrix(predictions, ground_truth, classes):
    num_classes = len(classes)
    confusion_matrix = [[0] * num_classes for _ in range(num_classes)]
   
    for predicted, actual in zip(predictions, ground_truth):
        predicted_index = classes.index(predicted)
        actual_index = classes.index(actual)
        confusion_matrix[predicted_index][actual_index] += 1

    return confusion_matrix

In [1871]:
print("Confusion Matrix: ")
calculate_confusion_matrix(predicted_values, truth_values,list(classes.keys()))

Confusion Matrix: 


[[54, 0, 0, 0, 0],
 [0, 29, 0, 0, 0],
 [0, 0, 44, 0, 0],
 [56, 52, 35, 100, 40],
 [0, 0, 0, 0, 37]]

(5) Improving the Classifier

In [1872]:
# Improving the preprocessing
def pre_data(Text):
  # Remove punctuation and replace '_' with space
  text=re.sub(r'[^\w\s]', '', Text).replace("_"," ")
  # remove stopwords
  text=remove_stopwords(text)
  # Remove extra spaces
  text = re.sub(r'\s+', ' ', text)
  # Remove digits
  text = re.sub(r'\d+', '', text)
  # Convert to lowercase
  text=text.lower()
  return text
df2['Text'] = df2['Text'].apply(pre_data)

def tok_lemm(Text):
  wordTokens=tokenize.RegexpTokenizer(r'\w+').tokenize(Text)
  finalTokens=[WordNetLemmatizer().lemmatize(w) for w in wordTokens]
  return finalTokens
df2=df2.drop(['Text_new'], axis=1)
df2['Text'] = df2['Text'].apply(tok_lemm)
df2

ArticleId                                               Text  \
0          1833  [worldcom, exboss, launch, defence, lawyer, de...   
1           154  [german, business, confidence, slide, german, ...   
2          1101  [bbc, poll, indicates, economic, gloom, citize...   
3          1976  [lifestyle, governs, mobile, choice, faster, b...   
4           917  [enron, boss, m, payout, eighteen, enron, dire...   
...         ...                                                ...   
1485        857  [double, eviction, big, brother, model, capric...   
1486        325  [dj, double, act, revamp, chart, dj, duo, jk, ...   
1487       1590  [weak, dollar, hit, reuters, revenue, medium, ...   
1488       1587  [apple, ipod, family, expands, market, apple, ...   
1489        538  [santy, worm, make, unwelcome, visit, thousand...   

           Category  
0          business  
1          business  
2          business  
3              tech  
4          business  
...             ...  
1485  entertainment  
1486  entertainment  
1487       business  
1488           tech  
1489           tech  

[1490 rows x 3 columns]

In [1873]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.naive_bayes import GaussianNB

def find_acc(x_train, x_test, y_train, y_test):
    # Create TF-IDF vectors
    vectorizer = TfidfVectorizer(ngram_range=(1,2))
    vec_x_train = vectorizer.fit_transform(x_train)
    vec_x_test = vectorizer.transform(x_test)

    # Gaussian Naive Bayes Classifier
    clf = GaussianNB()
    clf.fit(vec_x_train.toarray(), y_train)
    y_pred = clf.predict(vec_x_test.toarray())

    # Print results
    print("Confusion Matrix: ")
    cm = confusion_matrix(y_test, y_pred)
    print(cm)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1= f1_score(y_test, y_pred, average='weighted')
    print("Precision: ",precision )
    print("Recall: ",recall)
    print("f1_score: ", f1)
    accuracy = accuracy_score(y_test, y_pred)
    return accuracy


In [1874]:
splitting_ratio=[0.4,0.2,0.5]
for r in splitting_ratio: 
  x_train,x_test,y_train,y_test= train_test_split(df['Text'], df['Category'], test_size=r, random_state=43)
  Accuracy= find_acc(x_train,x_test,y_train, y_test)
  print("Accuracy: ",Accuracy)

Confusion Matrix: 
[[129   1   6   1   8]
 [  2 101   1   1   2]
 [  1   1 105   0   1]
 [  1   0   0 133   0]
 [  0   2   2   0  98]]
Precision:  0.9509359535433893
Recall:  0.9496644295302014
f1_score:  0.9495599480681839
Accuracy:  0.9496644295302014
Confusion Matrix: 
[[64  0  2  1  7]
 [ 2 48  0  1  3]
 [ 0  1 53  0  0]
 [ 0  0  0 68  0]
 [ 0  2  0  0 46]]
Precision:  0.939943567420867
Recall:  0.9362416107382551
f1_score:  0.9363032352739027
Accuracy:  0.9362416107382551
Confusion Matrix: 
[[151   1   8   0  10]
 [  1 129   0   0   4]
 [  1   1 130   0   0]
 [  1   0   0 172   0]
 [  0   6   3   0 127]]
Precision:  0.9531034573561706
Recall:  0.9516778523489933
f1_score:  0.9516096154488246
Accuracy:  0.9516778523489933
